# Generated by Django 2.2.6 on 2019-10-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minicursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dias', models.CharField(max_length=255)),
                ('horarios', models.CharField(max_length=255)),
                ('total_vagas', models.IntegerField()),
                ('vagas_disponiveis', models.IntegerField(default=0)),
                ('observacoes', models.TextField()),
            ],
            options={
                'verbose_name': 'Minicurso',
                'verbose_name_plural': 'Minicursos',
            },
        ),
        migrations.CreateModel(
            name='Palestrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Palestrante',
                'verbose_name_plural': 'Palestrantes',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instituicao', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('Estudante Graduação', 'Estudante Graduação'), ('Estudante de Pós-Gradução', 'Estudante de Pós-Gradução'), ('Docente', 'Docente'), ('Outros Profissionais', 'Outros Profissionais')], max_length=255)),
                ('minicurso', models.ManyToManyField(to='core.Minicursos')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
