# Generated by Django 2.2.6 on 2019-10-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicursos',
            name='responsavel',
            field=models.CharField(default='pombo', max_length=255),
        ),
    ]
