# Generated by Django 2.2.6 on 2019-10-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_minicursos_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicursos',
            name='responsavel',
            field=models.CharField(default='Não há', max_length=255),
        ),
    ]
