# Generated by Django 2.2.6 on 2019-10-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191004_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicursos',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
