# Generated by Django 2.2 on 2021-09-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricoes_ativas', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes',
            },
        ),
    ]
