# Generated by Django 2.2 on 2022-09-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ajustes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='curso1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='curso2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='curso3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='curso4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='curso5',
            field=models.BooleanField(default=False),
        ),
    ]
